version: "3"

networks:
    laravel:
        driver: bridge

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        ports:
            - "9000:80"
        volumes:
            - .:/var/www/app:delegated
        networks:
            - laravel
