version: '3.8'

services:
    app:
        build:
            context: .
        container_name: laravel_app
        restart: unless-stopped
        ports:
            - "8080:80"  # Exposing port 8080 to host, mapping to container port 80
        depends_on:
            - php
            - db
        networks:
            - laravel

    php:
        image: php:8.2-fpm
        container_name: laravel_php
        restart: unless-stopped
        volumes:
            - .:/var/www
        expose:
            - "9000"
        networks:
            - laravel

    db:
        image: mysql:5.7
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: atalanta
            MYSQL_ROOT_PASSWORD: Casa1992!
        ports:
            - "3307:3306"  # Change the host port from 3306 to 3307
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

volumes:
    db_data:

networks:
    laravel:
